#!/bin/sh

dev_flow_script_dir=${0%/*}
if [ "$dev_flow_script_dir" = "$0" ]; then
  dev_flow_script_dir=.
fi

exec \
  "$dev_flow_script_dir/dev_flow_python_launcher" \
  "$dev_flow_script_dir/dev_flow_mcp.py" \
  "$@"
